version: "3.8"
services:
  app:
    build:
      args:
        user: cristofer
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: machtecc
    container_name: machtecc-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - machtecc

  db:
    image: mysql:8
    container_name: machtecc-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33060:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - machtecc

  nginx:
    image: nginx:alpine
    container_name: machtecc-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - machtecc

networks:
  machtecc:
    driver: bridge
#docker-compose exec app composer install
#docker-compose exec app php artisan key:generate
